
name: Deploy CA Server

on:
  push:
    branches: [ca]

jobs:
  deploy_ca:
    if: github.repository == 'CATALOG-Historic-Records/orphaned-wells-ui-server' && vars.ENABLE_GKE_DEPLOYMENTS != 'true'
    uses: ./.github/workflows/deploy-dispatch.yml
    with:
      DEPLOY_ENV: ca
    secrets: inherit
