
name: Deploy ISGS Server

on:
  push:
    branches: [isgs]

jobs:
  deploy_isgs:
    if: github.repository == 'CATALOG-Historic-Records/orphaned-wells-ui-server'
    uses: CATALOG-Historic-Records/orphaned-wells-ui-server/.github/workflows/deploy.yml@main
    with:
      DEPLOY_ENV: isgs
    secrets: inherit
