name: Deploy Texas RRC Server to GKE

on:
  push:
    branches: [rrc]
  workflow_dispatch:

jobs:
  deploy_gke_rrc:
    if: github.repository == 'CATALOG-Historic-Records/orphaned-wells-ui-server' && (github.event_name == 'workflow_dispatch' || vars.ENABLE_GKE_DEPLOYMENTS == 'true')
    uses: ./.github/workflows/deploy-k8s-dispatch.yml
    with:
      DEPLOY_ENV: rrc
      IMAGE_TAG: auto
    secrets: inherit
