
name: Deploy NEWTS Server

on:
  push:
    branches: [newts]

jobs:
  deploy_newts:
    if: github.repository == 'CATALOG-Historic-Records/orphaned-wells-ui-server'
    uses: CATALOG-Historic-Records/orphaned-wells-ui-server/.github/workflows/deploy-dispatch.yml@main
    with:
      DEPLOY_ENV: newts
    secrets: inherit
