
name: Deploy CA Server

on:
  push:
    branches: [ca]

jobs:
  deploy_ca:
    if: github.repository == 'CATALOG-Historic-Records/orphaned-wells-ui-server'
    uses: CATALOG-Historic-Records/orphaned-wells-ui-server/.github/workflows/deploy.yml@main
    with:
      DEPLOY_ENV: ca
    secrets: inherit
