
name: Deploy OSAGE Server

on:
  push:
    branches: [osage]

jobs:
  deploy_osage:
    if: github.repository == 'CATALOG-Historic-Records/orphaned-wells-ui-server'
    uses: CATALOG-Historic-Records/orphaned-wells-ui-server/.github/workflows/deploy.yml@main
    with:
      DEPLOY_ENV: osage
    secrets: inherit
